# Generated by Django 5.0.3 on 2024-06-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dialogue',
            table='lesson_dialogue',
        ),
        migrations.CreateModel(
            name='Replica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('interlocutor_a', models.TextField()),
                ('interlocutor_b', models.TextField()),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.dialogue')),
            ],
            options={
                'db_table': 'lesson_replica',
            },
        ),
        migrations.AddField(
            model_name='dialogue',
            name='replicas',
            field=models.ManyToManyField(related_name='dialogues', to='lesson.replica'),
        ),
    ]
