# Generated by Django 5.0.3 on 2024-06-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_dialogue_table_replica_dialogue_replicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replica',
            name='interlocutor_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='replica',
            name='interlocutor_b',
            field=models.TextField(blank=True, null=True),
        ),
    ]
