# Generated by Django 5.0.3 on 2024-06-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_alter_replica_interlocutor_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='replicas',
            field=models.ManyToManyField(blank=True, null=True, related_name='dialogues', to='lesson.replica'),
        ),
    ]
