# Generated by Django 5.0.3 on 2024-06-08 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_alter_dialogue_replicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('word', models.TextField()),
                ('translation', models.TextField()),
                ('analysis', models.TextField()),
                ('replica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.replica')),
            ],
            options={
                'db_table': 'lesson_word_analysis',
            },
        ),
        migrations.AddField(
            model_name='replica',
            name='replica_analysis',
            field=models.ManyToManyField(blank=True, null=True, related_name='replicas', to='lesson.wordanalysis'),
        ),
    ]
