# Generated by Django 5.0.3 on 2024-06-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_wordanalysis_replica_replica_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='replicas',
            field=models.ManyToManyField(blank=True, related_name='dialogues', to='lesson.replica'),
        ),
    ]
