# Generated by Django 5.0.3 on 2024-06-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_alter_replica_replica_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replica',
            name='replica_analysis',
        ),
        migrations.AddField(
            model_name='replica',
            name='interlocutor_a_analysis',
            field=models.ManyToManyField(blank=True, related_name='replicas_a_analysis', to='lesson.wordanalysis'),
        ),
        migrations.AddField(
            model_name='replica',
            name='interlocutor_b_analysis',
            field=models.ManyToManyField(blank=True, related_name='replicas_b_analysis', to='lesson.wordanalysis'),
        ),
    ]
