# Generated by Django 5.0.3 on 2024-06-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_remove_exercise_section_exercise_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordanalysis',
            name='replica',
        ),
    ]
