# Generated by Django 5.0.3 on 2024-06-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_remove_wordanalysis_replica'),
    ]

    operations = [
        migrations.AddField(
            model_name='replica',
            name='translater_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replica',
            name='translater_b',
            field=models.TextField(blank=True, null=True),
        ),
    ]
