# Generated by Django 5.0.3 on 2024-06-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_replica_translater_a_replica_translater_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainer/images/'),
        ),
    ]
