# Generated by Django 5.0.3 on 2024-05-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(max_length=100)),
                ('season_number', models.IntegerField(verbose_name='Season Number')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('series_number', models.IntegerField(verbose_name='Series Number')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('dash_path', models.CharField(max_length=1000)),
                ('hls_path', models.CharField(max_length=1000)),
                ('ru_subt_path', models.CharField(max_length=1000)),
                ('en_subt_path', models.CharField(max_length=1000)),
                ('subt_path', models.JSONField()),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(max_length=100)),
                ('plot', models.TextField(max_length=1000)),
                ('rating', models.FloatField(default=0)),
                ('release_year', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('poster_image', models.ImageField(null=True, upload_to='poster/', verbose_name='movie poster')),
                ('poster_path', models.CharField(max_length=1000)),
                ('countries', models.ManyToManyField(related_name='countries', to='movie.country')),
                ('genre', models.ManyToManyField(to='movie.genre')),
                ('seasons', models.ManyToManyField(related_name='seasons', to='movie.season')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ManyToManyField(related_name='series', to='movie.series'),
        ),
    ]
